# Generated by Django 5.2.4 on 2025-07-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
