# Generated by Django 5.2.4 on 2025-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='zoom_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
