# Generated by Django 5.2.4 on 2025-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_detail_url_alter_event_zoom_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
