# Generated by Django 5.2.4 on 2025-08-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='homework',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='next_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
