# Generated by Django 5.2.4 on 2025-08-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
