# Generated by Django 5.2.4 on 2025-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_alter_past_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='past',
            old_name='url',
            new_name='presentation_url',
        ),
        migrations.AddField(
            model_name='past',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
