# Generated by Django 5.2.4 on 2025-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
