# Generated by Django 5.2.4 on 2025-08-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_alter_knowledge_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='content',
            field=models.TextField(),
        ),
    ]
