# Generated by Django 5.2.4 on 2025-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
