# Generated by Django 5.2.4 on 2025-07-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='team_id',
            new_name='team',
        ),
    ]
