# Generated by Django 5.2.4 on 2025-08-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_assignee_id_task_assignee_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
            preserve_default=False,
        ),
    ]
